In [100]:
import numpy as np
import pandas as pd

In [101]:
df = pd.read_csv('/content/faa_ai_prelim.csv')

In [102]:
df

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,No,08-FEB-16,31-DEC-15,17:00:00Z,SAN ANTONIO,Texas,NaN,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",Accident,FAA San Antonio FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
df.describe()

,ACFT_MISSING_FLAG,FAR_PART,FLT_CRW_INJ_NONE,FLT_CRW_INJ_MINOR,FLT_CRW_INJ_SERIOUS,FLT_CRW_INJ_FATAL,FLT_CRW_INJ_UNK,CBN_CRW_INJ_NONE,CBN_CRW_INJ_MINOR,CBN_CRW_INJ_SERIOUS,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
count,0.0,1.0,64.000000,6.000000,1.0,8.000000,0.0,0.0,0.0,0.0,...,17.000000,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
mean,NaN,91.0,1.218750,1.333333,3.0,1.500000,NaN,NaN,NaN,NaN,...,1.823529,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
std,NaN,NaN,0.700765,0.516398,NaN,0.534522,NaN,NaN,NaN,NaN,...,1.236694,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
25%,NaN,91.0,1.000000,1.000000,3.0,1.000000,NaN,NaN,NaN,NaN,...,1.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
50%,NaN,91.0,1.000000,1.000000,3.0,1.500000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
75%,NaN,91.0,1.000000,1.750000,3.0,2.000000,NaN,NaN,NaN,NaN,...,2.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0
max,NaN,91.0,6.000000,2.000000,3.0,2.000000,NaN,NaN,NaN,NaN,...,6.000000,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              83 non-null     object
 1   ENTRY_DATE           83 non-null     object
 2   EVENT_LCL_DATE       83 non-null     object
 3   EVENT_LCL_TIME       83 non-null     object
 4   LOC_CITY_NAME        83 non-null     object
 5   LOC_STATE_NAME       83 non-null     object
 6   LOC_CNTRY_NAME       2 non-null      object
 7   RMK_TEXT             83 non-null     object
 8   EVENT_TYPE_DESC      83 non-null     object
 9   FSDO_DESC            81 non-null     object
 10  REGIST_NBR           83 non-null     object
 11  FLT_NBR              6 non-null      object
 12  ACFT_OPRTR           7 non-null      object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      79 non-null     object
 15  ACFT_MISSING_FLAG    0 non-null      float64
 16  ACFT_DMG_DESC        74 non-null     object
 17  FLT_ACTIVITY         13 non-null     object
 18  FLT_PHASE            82 non-null     object
 19  FAR_PART             1 non-null      float64
 20  MAX_INJ_LVL          19 non-null     object
 21  FATAL_FLAG           8 non-null      object
 22  FLT_CRW_INJ_NONE     64 non-null     float64
 23  FLT_CRW_INJ_MINOR    6 non-null      float64
 24  FLT_CRW_INJ_SERIOUS  1 non-null      float64
 25  FLT_CRW_INJ_FATAL    8 non-null      float64
 26  FLT_CRW_INJ_UNK      0 non-null      float64
 27  CBN_CRW_INJ_NONE     0 non-null      float64
 28  CBN_CRW_INJ_MINOR    0 non-null      float64
 29  CBN_CRW_INJ_SERIOUS  0 non-null      float64
 30  CBN_CRW_INJ_FATAL    0 non-null      float64
 31  CBN_CRW_INJ_UNK      1 non-null      float64
 32  PAX_INJ_NONE         17 non-null     float64
 33  PAX_INJ_MINOR        1 non-null      float64
 34  PAX_INJ_SERIOUS      3 non-null      float64
 35  PAX_INJ_FATAL        1 non-null      float64
 36  PAX_INJ_UNK          0 non-null      float64
 37  GRND_INJ_NONE        0 non-null      float64
 38  GRND_INJ_MINOR       0 non-null      float64
 39  GRND_INJ_SERIOUS     0 non-null      float64
 40  GRND_INJ_FATAL       0 non-null      float64
 41  GRND_INJ_UNK         1 non-null      float64
dtypes: float64(22), object(20)
memory usage: 27.4+ KB

In [105]:
# Convert date and time columns to datetime objects
df['EVENT_LCL_DATE'] = pd.to_datetime(df['EVENT_LCL_DATE'])
df['EVENT_LCL_TIME'] = pd.to_datetime(df['EVENT_LCL_TIME'].str.replace('Z', ''), format='%H:%M:%S', errors='coerce').dt.time

# Combine date and time into a single datetime column
df['EVENT_DATETIME'] = df.apply(lambda row: pd.Timestamp.combine(row['EVENT_LCL_DATE'], row['EVENT_LCL_TIME']) if pd.notna(row['EVENT_LCL_TIME']) else row['EVENT_LCL_DATE'], axis=1)

# Display the updated dataframe with the new datetime column
display(df[['EVENT_LCL_DATE', 'EVENT_LCL_TIME', 'EVENT_DATETIME']].head())

/tmp/ipython-input-3992355297.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['EVENT_LCL_DATE'] = pd.to_datetime(df['EVENT_LCL_DATE'])

  EVENT_LCL_DATE EVENT_LCL_TIME      EVENT_DATETIME
0     2016-02-19       00:45:00 2016-02-19 00:45:00
1     2016-02-18       23:55:00 2016-02-18 23:55:00
2     2016-02-18       22:14:00 2016-02-18 22:14:00
3     2016-02-18       17:10:00 2016-02-18 17:10:00
4     2016-02-18       00:26:00 2016-02-18 00:26:00

In [106]:
df.head()

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK,EVENT_DATETIME
0,No,19-FEB-16,2016-02-19,00:45:00,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-02-19 00:45:00
1,No,19-FEB-16,2016-02-18,23:55:00,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-02-18 23:55:00
2,No,19-FEB-16,2016-02-18,22:14:00,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-02-18 22:14:00
3,No,19-FEB-16,2016-02-18,17:10:00,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-02-18 17:10:00
4,No,19-FEB-16,2016-02-18,00:26:00,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-02-18 00:26:00

In [107]:
df.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK',
       'EVENT_DATETIME'],
      dtype='object')

In [108]:
req_cols = ['ACFT_MAKE_NAME','LOC_STATE_NAME','ACFT_MODEL_NAME','RMK_TEXT','FLT_PHASE','EVENT_TYPE_DESC','FATAL_FLAG','ACFT_DMG_DESC']

In [109]:
df_new = df[req_cols]

In [110]:
df_new

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_DMG_DESC
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes,Unknown
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN,Unknown
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN,Minor
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN,Unknown
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN,Minor
...,...,...,...,...,...,...,...,...
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,NaN,Substantial
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes,Destroyed
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,Destroyed
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,Destroyed
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes,Unknown

In [111]:
df_new['FATAL_FLAG'] = df_new['FATAL_FLAG'].fillna('No')

/tmp/ipython-input-3286040453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['FATAL_FLAG'] = df_new['FATAL_FLAG'].fillna('No')

In [112]:
flt_phase_mode = df_new['FLT_PHASE'].mode()[0]
df_new['FLT_PHASE'] = df_new['FLT_PHASE'].fillna(flt_phase_mode)
acft_dmg_desc_mode = df_new['ACFT_DMG_DESC'].mode()[0]
df_new['ACFT_DMG_DESC'] = df_new['ACFT_DMG_DESC'].fillna(acft_dmg_desc_mode)

/tmp/ipython-input-3352087900.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['FLT_PHASE'] = df_new['FLT_PHASE'].fillna(flt_phase_mode)
/tmp/ipython-input-3352087900.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['ACFT_DMG_DESC'] = df_new['ACFT_DMG_DESC'].fillna(acft_dmg_desc_mode)

In [113]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   78 non-null     object
 1   LOC_STATE_NAME   83 non-null     object
 2   ACFT_MODEL_NAME  79 non-null     object
 3   RMK_TEXT         83 non-null     object
 4   FLT_PHASE        83 non-null     object
 5   EVENT_TYPE_DESC  83 non-null     object
 6   FATAL_FLAG       83 non-null     object
 7   ACFT_DMG_DESC    83 non-null     object
dtypes: object(8)
memory usage: 5.3+ KB

In [114]:
orig = df_new.shape
orig

(83, 8)

In [115]:
df_new = df_new.dropna()

In [116]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 0 to 82
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   77 non-null     object
 1   LOC_STATE_NAME   77 non-null     object
 2   ACFT_MODEL_NAME  77 non-null     object
 3   RMK_TEXT         77 non-null     object
 4   FLT_PHASE        77 non-null     object
 5   EVENT_TYPE_DESC  77 non-null     object
 6   FATAL_FLAG       77 non-null     object
 7   ACFT_DMG_DESC    77 non-null     object
dtypes: object(8)
memory usage: 5.4+ KB

In [117]:
print(f'New shape: {df_new.shape}\nOriginal Shape: {orig}')

New shape: (77, 8)
Original Shape: (83, 8)

In [118]:
df_new['ACFT_MODEL_NAME'].value_counts()

ACFT_MODEL_NAME
172              4
210              4
206              3
36               3
150              3
PA34             3
PA28             3
35               3
737              2
310              2
PA24             2
152              2
M20K             2
182              2
8KCAB            2
T34              1
235              1
EAGLE II         1
747              1
RV7              1
2T1A             1
PA20             1
GC1B             1
369              1
340              1
560              1
PT19             1
BT15             1
55               1
M20M             1
140              1
S2               1
RX8              1
ERJ190           1
M4               1
TB9              1
A319             1
47G              1
180              1
AA1              1
CTLS             1
33               1
GULFSTREAM200    1
TB21             1
PA31             1
175              1
IV               1
500              1
M20E             1
NA265            1
O58B             1
F51              1
Name: count, dtype: int64

In [119]:
df_new['ACFT_MAKE_NAME'].value_counts()

ACFT_MAKE_NAME
CESSNA                    23
PIPER                     10
BEECH                      9
MOONEY                     4
BOEING                     3
BELL                       2
CHAMPION                   2
SOCATA                     2
LANCAIR                    2
GLOBE                      1
VANS                       1
CHRISTEN                   1
HUGHES                     1
FAIRCHILD                  1
CONSOLIDATED VULTEE        1
GREAT LAKES                1
SAAB                       1
MAULE                      1
EMBRAER                    1
PITTS                      1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
GRUMMAN                    1
GULFSTREAM                 1
FLIGHT DESIGN              1
AERO COMMANDER             1
SABRELINER                 1
AERONCA                    1
NORTH AMERICAN             1
Name: count, dtype: int64

In [120]:
df_new.loc[(df_new['FATAL_FLAG']=='Yes')]

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG,ACFT_DMG_DESC
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes,Unknown
53,PIPER,Florida,PA28,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,UNKNOWN (UNK),Accident,Yes,Destroyed
55,FLIGHT DESIGN,California,CTLS,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,UNKNOWN (UNK),Accident,Yes,Destroyed
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes,Destroyed
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,Destroyed
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes,Destroyed
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes,Unknown

In [121]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77 entries, 0 to 82
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ACFT_MAKE_NAME   77 non-null     object
 1   LOC_STATE_NAME   77 non-null     object
 2   ACFT_MODEL_NAME  77 non-null     object
 3   RMK_TEXT         77 non-null     object
 4   FLT_PHASE        77 non-null     object
 5   EVENT_TYPE_DESC  77 non-null     object
 6   FATAL_FLAG       77 non-null     object
 7   ACFT_DMG_DESC    77 non-null     object
dtypes: object(8)
memory usage: 5.4+ KB

In [122]:
df_new['ACFT_DMG_DESC'].unique()

array(['Unknown', 'Minor', 'Substantial', 'Destroyed'], dtype=object)

In [123]:
acft_dmg_desc_unknown = []
acft_dmg_desc_minor = []
acft_dmg_desc_substantial = []
acft_dmg_desc_destroyed = []
cols = [acft_dmg_desc_unknown,]
for row in df_new['ACFT_DMG_DESC']:
  if row=='Unknown':
    acft_dmg_desc_unknown.append(1)
    acft_dmg_desc_minor.append(0)
    acft_dmg_desc_substantial.append(0)
    acft_dmg_desc_destroyed.append(0)
  else:
    acft_dmg_desc_unknown.append(0)
    if row=='Minor':
      acft_dmg_desc_minor.append(1)
      acft_dmg_desc_substantial.append(0)
      acft_dmg_desc_destroyed.append(0)
    else:
      acft_dmg_desc_minor.append(0)
      if row=='Substantial':
        acft_dmg_desc_substantial.append(1)
        acft_dmg_desc_destroyed.append(0)
      else:
        acft_dmg_desc_substantial.append(0)
        acft_dmg_desc_destroyed.append(1)

In [124]:
df_new['ACFT_DMG_DESC_UNKNOWN'] = pd.Series(acft_dmg_desc_unknown,index=df_new.index)
df_new['ACFT_DMG_DESC_MINOR'] = pd.Series(acft_dmg_desc_minor,index=df_new.index)
df_new['ACFT_DMG_DESC_SUBSTANTIAL'] = pd.Series(acft_dmg_desc_substantial,index=df_new.index)
df_new['ACFT_DMG_DESC_DESTROYED'] = pd.Series(acft_dmg_desc_destroyed,index=df_new.index)

/tmp/ipython-input-2765286661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['ACFT_DMG_DESC_UNKNOWN'] = pd.Series(acft_dmg_desc_unknown,index=df_new.index)
/tmp/ipython-input-2765286661.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['ACFT_DMG_DESC_MINOR'] = pd.Series(acft_dmg_desc_minor,index=df_new.index)
/tmp/ipython-input-2765286661.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['ACFT_DMG_DESC_SUBSTANTIAL'] = pd.Series(acft_dmg_desc_substantial,index=df_new.index)
/tmp/ipython-input-2765286661.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['ACFT_DMG_DESC_DESTROYED'] = pd.Series(acft_dmg_desc_destroyed,index=df_new.index)

In [125]:
flt_phase_text = []
possible_phase = ["LANDING", "TAKEOFF", "CRUISE","APPROACH"]
for i in df_new.index: # Iterate over the indices of df_new
  rmk_text = df_new.loc[i,'RMK_TEXT']
  flag = False
  for phase in possible_phase:
    if phase in rmk_text:
      flt_phase_text.append(phase)
      flag = True
      break
  if not flag:
    flt_phase_text.append("UNKNOWN")

In [126]:
df_new['FLT_PHASE_TEXT'] = pd.Series(flt_phase_text,index=df_new.index)

/tmp/ipython-input-2486868592.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['FLT_PHASE_TEXT'] = pd.Series(flt_phase_text,index=df_new.index)

In [127]:
cols = ['FLT_PHASE','FLT_PHASE_TEXT']
df_new[cols]

         FLT_PHASE FLT_PHASE_TEXT
0    UNKNOWN (UNK)        UNKNOWN
1    LANDING (LDG)        LANDING
2   APPROACH (APR)        UNKNOWN
3    LANDING (LDG)        LANDING
4    LANDING (LDG)        LANDING
..             ...            ...
78   LANDING (LDG)        LANDING
79   UNKNOWN (UNK)        UNKNOWN
80   UNKNOWN (UNK)        UNKNOWN
81   UNKNOWN (UNK)        UNKNOWN
82   UNKNOWN (UNK)        UNKNOWN

[77 rows x 2 columns]